-- MySQL Script generated by MySQL Workbench
-- Mon Oct  6 14:24:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`instituciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instituciones` (
  `idinstituciones` INT NOT NULL AUTO_INCREMENT,
  `nombre_institucion` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `updated_by` INT NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idinstituciones`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `fecha_nac` DATE NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `updated_by` INT NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `instituciones_idinstituciones` INT NOT NULL,
  PRIMARY KEY (`idusuarios`),
  INDEX `fk_usuarios_instituciones_idx` (`instituciones_idinstituciones` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_instituciones`
    FOREIGN KEY (`instituciones_idinstituciones`)
    REFERENCES `mydb`.`instituciones` (`idinstituciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materias` (
  `idmaterias` INT NOT NULL AUTO_INCREMENT,
  `nombre_materias` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `updated_by` INT NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  `instituciones_idinstituciones` INT NOT NULL,
  PRIMARY KEY (`idmaterias`),
  INDEX `fk_materias_instituciones1_idx` (`instituciones_idinstituciones` ASC) VISIBLE,
  CONSTRAINT `fk_materias_instituciones1`
    FOREIGN KEY (`instituciones_idinstituciones`)
    REFERENCES `mydb`.`instituciones` (`idinstituciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personas` (
  `idpersonas` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `nivel_de_acceso` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `updated_by` INT NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idpersonas`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`tip_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tip_usuarios` (
  `idtip_usuarios` INT NOT NULL AUTO_INCREMENT,
  `personas_idpersonas` INT NOT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_by` INT NOT NULL,
  `updated_by` INT NOT NULL,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idtip_usuarios`),
  INDEX `fk_tip_usuarios_personas1_idx` (`personas_idpersonas` ASC) VISIBLE,
  INDEX `fk_tip_usuarios_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_tip_usuarios_personas1`
    FOREIGN KEY (`personas_idpersonas`)
    REFERENCES `mydb`.`personas` (`idpersonas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tip_usuarios_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`credeciales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`credeciales` (
  `idcredeciales` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idcredeciales`),
  INDEX `fk_credeciales_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_credeciales_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alumnos` (
  `idalumnos` INT NOT NULL AUTO_INCREMENT,
  `fecha_ingreso` DATE NOT NULL,
  `condicion` TINYINT NOT NULL,
  `observaciones` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  `instituciones_idinstituciones` INT NOT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idalumnos`),
  INDEX `fk_alumnos_instituciones1_idx` (`instituciones_idinstituciones` ASC) VISIBLE,
  INDEX `fk_alumnos_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_alumnos_instituciones1`
    FOREIGN KEY (`instituciones_idinstituciones`)
    REFERENCES `mydb`.`instituciones` (`idinstituciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnos_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`calificaciones` (
  `idcalificaciones` INT NOT NULL AUTO_INCREMENT,
  `calificacion` DECIMAL(3,1) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  `alumnos_idalumnos` INT NOT NULL,
  PRIMARY KEY (`idcalificaciones`),
  INDEX `fk_calificaciones_alumnos1_idx` (`alumnos_idalumnos` ASC) VISIBLE,
  CONSTRAINT `fk_calificaciones_alumnos1`
    FOREIGN KEY (`alumnos_idalumnos`)
    REFERENCES `mydb`.`alumnos` (`idalumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actividades` (
  `idactividades` INT NOT NULL AUTO_INCREMENT,
  `nombre_actividad` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `tipo_actividad` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  `materias_idmaterias` INT NOT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  `calificaciones_idcalificaciones` INT NOT NULL,
  PRIMARY KEY (`idactividades`),
  INDEX `fk_actividades_materias1_idx` (`materias_idmaterias` ASC) VISIBLE,
  INDEX `fk_actividades_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  INDEX `fk_actividades_calificaciones1_idx` (`calificaciones_idcalificaciones` ASC) VISIBLE,
  CONSTRAINT `fk_actividades_materias1`
    FOREIGN KEY (`materias_idmaterias`)
    REFERENCES `mydb`.`materias` (`idmaterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividades_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividades_calificaciones1`
    FOREIGN KEY (`calificaciones_idcalificaciones`)
    REFERENCES `mydb`.`calificaciones` (`idcalificaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`historial_rendimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historial_rendimientos` (
  `idhistorial_rendimientos` INT NOT NULL AUTO_INCREMENT,
  `promedio_general` DECIMAL(3,1) NOT NULL,
  `periodo` VARCHAR(45) NOT NULL,
  `ano` INT NOT NULL,
  `tendencia` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  `alumnos_idalumnos` INT NOT NULL,
  PRIMARY KEY (`idhistorial_rendimientos`),
  INDEX `fk_historial_rendimientos_alumnos1_idx` (`alumnos_idalumnos` ASC) VISIBLE,
  CONSTRAINT `fk_historial_rendimientos_alumnos1`
    FOREIGN KEY (`alumnos_idalumnos`)
    REFERENCES `mydb`.`alumnos` (`idalumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`profesores_materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`profesores_materias` (
  `idprofesores_materias` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  `usuarios_idusuarios` INT NOT NULL,
  `materias_idmaterias` INT NOT NULL,
  PRIMARY KEY (`idprofesores_materias`),
  INDEX `fk_profesores_materias_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  INDEX `fk_profesores_materias_materias1_idx` (`materias_idmaterias` ASC) VISIBLE,
  CONSTRAINT `fk_profesores_materias_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesores_materias_materias1`
    FOREIGN KEY (`materias_idmaterias`)
    REFERENCES `mydb`.`materias` (`idmaterias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`cursos_capacitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos_capacitaciones` (
  `idcursos_capacitaciones` INT NOT NULL AUTO_INCREMENT,
  `titulo_curso` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `durante_horas` INT NOT NULL,
  `tipo_contenido` VARCHAR(45) NOT NULL,
  `url_contenido` VARCHAR(450) NOT NULL,
  `fecha_publicacion` DATETIME NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idcursos_capacitaciones`),
  INDEX `fk_cursos_capacitaciones_usuarios1_idx` (`usuarios_idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_capacitaciones_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`redes_sociales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`redes_sociales` (
  `idredes_sociales` INT NOT NULL AUTO_INCREMENT,
  `nombre_red` VARCHAR(45) NOT NULL,
  `url_api` VARCHAR(45) NOT NULL,
  `credenciales` VARCHAR(45) NOT NULL,
  `activa` TINYINT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idredes_sociales`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`publicaciones_redes_sociales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publicaciones_redes_sociales` (
  `idpublicaciones_redes_sociales` INT NOT NULL AUTO_INCREMENT,
  `contenido` VARCHAR(45) NOT NULL,
  `fecha_program` DATETIME NOT NULL,
  `fecha_pub` DATETIME NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL,
  `deleted` TINYINT NULL DEFAULT 0,
  `cursos_capacitaciones_idcursos_capacitaciones` INT NOT NULL,
  `redes_sociales_idredes_sociales` INT NOT NULL,
  PRIMARY KEY (`idpublicaciones_redes_sociales`),
  INDEX `fk_publicaciones_redes_sociales_cursos_capacitaciones1_idx` (`cursos_capacitaciones_idcursos_capacitaciones` ASC) VISIBLE,
  INDEX `fk_publicaciones_redes_sociales_redes_sociales1_idx` (`redes_sociales_idredes_sociales` ASC) VISIBLE,
  CONSTRAINT `fk_publicaciones_redes_sociales_cursos_capacitaciones1`
    FOREIGN KEY (`cursos_capacitaciones_idcursos_capacitaciones`)
    REFERENCES `mydb`.`cursos_capacitaciones` (`idcursos_capacitaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publicaciones_redes_sociales_redes_sociales1`
    FOREIGN KEY (`redes_sociales_idredes_sociales`)
    REFERENCES `mydb`.`redes_sociales` (`idredes_sociales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;